baseurl = "https://aazannoorkhuwaja.github.io/"
title = "Aazan Noor Khuwaja"
theme = "blowfish"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true
summaryLength = 0

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[Permalinks]
  post = "/:contentbasename/"
